# The port on which Cynthia hosts, since Cynthia was designed to be reverse-proxied, this port is usually higher than 1000.
PORT = 3020
[cache]
# These rules are set for a reason: The higher they are set, the less requests we have to do to Node, external servers, etc.
# High caching lifetimes can speed up Cynthia a whole lot, so think wisely before you lower any of these numbers!
[cache.lifetimes]

# How long (in seconds) to cache a CSS file after having minified and served it.
stylesheets = 72000

# How long (in seconds) to cache a JS file after having minified and served it.
javascript = 72000

# How long (in seconds) to cache an external output after having used it.
external = 1400

# How long should a fully-ready-to-be-served page be cached?
served = 10

# Generator rules set how Cynthia generates web pages.
[generator]
site-baseurl = "strawmelonjuice.com"
og-site-name = "strawmelonjuice dot com"
[generator.meta]

# Enables or disables pagetags in HTML metatags, these are officially supposed to be good for finding a website, but have been known to 
enable-tags = false
[logging]

# I'd advise you keep this enabled.
enabled = true

# Log about caching
cache = false

# Show errors in console
error = true

# Show warnings in console
warn = true

# Showing INFO blocks in console
info = true

# Should information about requests to Cynthia be shown in console?  
requests = true

# Should plugins that are proxied be shown in console?
proxy-requests = false

# Should files served to plugins be shown in console?
plugin-asset-requests = false

# JSR log items
jsr-errors = true

[pages]
404-page = "404"

